version: "3.8"
services:
  goldify:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: 3000
    container_name: "goldify"
    volumes:
      - "/app/node_modules"
      - ".:/app"
