version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      HOST: "0.0.0.0"
      PORT: 3000
    volumes:
      - "/app/node_modules"
      - "..:/app"