name: Goldify CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
      - run: yarn install
      - run: yarn start
      - run: yarn lint
      - run: yarn test
